CREATE TABLE typ_grafiki(
    grafika TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE status_seansu(
    status TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE typ_dzwieku(
    dzwiek TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE klient(
    id_klient INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    imie TEXT NOT NULL,
    nazwisko TEXT NOT NULL,
    mail TEXT UNIQUE NOT NULL,
    haslo TEXT NOT NULL CHECK (length(haslo) >= 8),
    nr_karty_czlonkowskiej INTEGER UNIQUE
);

CREATE TABLE pracownik(
    id_pracownik INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    imie TEXT NOT NULL,
    nazwisko TEXT NOT NULL,
    data_zatrudnienia DATE NOT NULL,
    telefon INTEGER UNIQUE NOT NULL,
    mail TEXT UNIQUE NOT NULL
);

CREATE TABLE sala(
    id_sali INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nr_sali INTEGER NOT NULL,
    liczba_miejsc INTEGER NOT NULL CHECK(liczba_miejsc >= 5),
    pietro INTEGER NOT NULL CHECK(pietro >= 0 AND pietro <= 2)
);

CREATE TABLE siedzenie(
    id_siedzenia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nr_miejsca INTEGER NOT NULL,
    nr_rzedu INTEGER NOT NULL,
    cena DECIMAL(5, 2) NOT NULL CHECK(cena >= 0),
    id_sali INTEGER NOT NULL,
    FOREIGN KEY (id_sali) REFERENCES sala(id_sali) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ograniczenia(
    ograniczenia_wiekowe TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE rezyser(
    id_rezyser INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    imie TEXT NOT NULL,
    nazwisko TEXT NOT NULL,
    rok_urodzenia INTEGER NOT NULL,
    rok_smierci INTEGER CHECK(rok_urodzenia < rok_smierci)
);

CREATE TABLE aktor(
    id_aktor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    imie TEXT NOT NULL,
    nazwisko TEXT NOT NULL,
    rok_urodzenia INTEGER NOT NULL,
    rok_smierci INTEGER CHECK(rok_urodzenia < rok_smierci)
);

CREATE TABLE gatunek(
    id_gatunek INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nazwa_gatunku TEXT UNIQUE NOT NULL
);

CREATE TABLE film(
    id_film INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    tytul TEXT NOT NULL,
    oryginalny_tytul TEXT,
    opis TEXT,
    dlugosc INTEGER NOT NULL CHECK(dlugosc >= 15),
    kraj_produkcji TEXT NOT NULL,
    data_premiery DATE NOT NULL,
    id_rezyser INTEGER,
    ograniczenia_wiekowe TEXT NOT NULL,
    FOREIGN KEY (id_rezyser) REFERENCES rezyser(id_rezyser) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (ograniczenia_wiekowe) REFERENCES ograniczenia(ograniczenia_wiekowe) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE aktorzy_w_filmie(
    id_aktor INTEGER NOT NULL,
    id_film INTEGER NOT NULL,
    FOREIGN KEY (id_aktor) REFERENCES aktor(id_aktor) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_film) REFERENCES film(id_film) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT pk_aktorzy_w_filmie PRIMARY KEY (id_aktor, id_film)
);

CREATE TABLE jaki_gatunek(
    id_gatunek INTEGER NOT NULL,
    id_film INTEGER NOT NULL,
    FOREIGN KEY (id_gatunek) REFERENCES gatunek(id_gatunek) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_film) REFERENCES film(id_film) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT pk_jaki_gatunek PRIMARY KEY (id_gatunek, id_film)
);

CREATE TABLE seans(
    id_seans INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    data DATE NOT NULL,
    godzina TIME NOT NULL,
    id_sali INTEGER NOT NULL,
    id_film INTEGER NOT NULL,
    grafika TEXT NOT NULL DEFAULT '2D',
    dzwiek TEXT,
    status TEXT NOT NULL DEFAULT 'za malo osob',
    FOREIGN KEY (id_sali) REFERENCES sala(id_sali) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_film) REFERENCES film(id_film) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (grafika) REFERENCES typ_grafiki(grafika) ON UPDATE CASCADE ON DELETE SET DEFAULT,
    FOREIGN KEY (dzwiek) REFERENCES typ_dzwieku(dzwiek) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (status) REFERENCES status_seansu ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE status_rezerwacja(
    status TEXT PRIMARY KEY NOT NULL
);

CREATE TABLE rezerwacja(
    id_rezerwacja INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    czy_oplacona BOOLEAN NOT NULL DEFAULT FALSE,
    id_seans INTEGER NOT NULL,
    id_klient INTEGER NOT NULL,
    id_siedzenia INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'nieaktywna',
    FOREIGN KEY (status) REFERENCES status_rezerwacja(status) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_seans) REFERENCES seans(id_seans) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_klient) REFERENCES klient(id_klient) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_siedzenia) REFERENCES siedzenie(id_siedzenia) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE gdzie_praca(
    id_pracownik INTEGER NOT NULL,
    id_seans INTEGER NOT NULL,
    FOREIGN KEY (id_pracownik) REFERENCES pracownik(id_pracownik) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_seans) REFERENCES seans(id_seans) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT pk_gdzie_praca PRIMARY KEY (id_pracownik, id_seans)
);

CREATE OR REPLACE FUNCTION usuwanie_rezerwacji()
RETURNS TRIGGER AS $$
    DECLARE
    status_seansu TEXT;
    BEGIN
        SELECT status INTO status_seansu FROM seans WHERE id_seans = OLD.id_seans;
        IF (OLD.status = 'aktywna') THEN
            RAISE EXCEPTION 'Nie mozesz usunac aktywnej rezerwacji.';
        END IF;
        IF (OLD.status = 'nieaktywna' AND status_seansu = 'nieaktywny') THEN
            RAISE EXCEPTION 'Nie mozesz usunac rezerwacji, ktore juz sie odbyly.';
        END IF;
        RETURN OLD;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER ur BEFORE DELETE ON rezerwacja FOR EACH ROW EXECUTE PROCEDURE usuwanie_rezerwacji();

CREATE OR REPLACE FUNCTION status_seans_miejsca()
RETURNS TRIGGER AS $$
    DECLARE 
    ile_rez INTEGER;
    BEGIN
        SELECT count(*) INTO ile_rez FROM rezerwacja WHERE id_seans = NEW.id_seans GROUP BY id_seans;
        IF (ile_rez >= 5) THEN
            UPDATE seans SET status = 'aktywny' WHERE id_seans = NEW.id_seans;
            UPDATE rezerwacja SET status = 'aktywna' WHERE id_seans = NEW.id_seans AND czy_oplacona = TRUE AND status != 'aktywna';
        END IF;
    RETURN NEW;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER ssm AFTER INSERT ON rezerwacja FOR EACH ROW EXECUTE PROCEDURE status_seans_miejsca();

CREATE OR REPLACE FUNCTION status_seans_miejsca_us()
RETURNS TRIGGER AS $$
    DECLARE 
    ile_rez INTEGER;
    BEGIN
        SELECT count(*) INTO ile_rez FROM rezerwacja WHERE id_seans = OLD.id_seans GROUP BY id_seans;
        IF (ile_rez < 5) THEN
            UPDATE seans SET status = 'za malo osob' WHERE id_seans = OLD.id_seans;
            UPDATE rezerwacja SET status = 'nieaktywna' WHERE id_seans = OLD.id_seans AND status = 'aktywna';
        END IF;
    RETURN OLD;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER ssmu AFTER DELETE ON rezerwacja FOR EACH ROW EXECUTE PROCEDURE status_seans_miejsca_us();

CREATE OR REPLACE FUNCTION oplacanie_rezerwacji()
RETURNS TRIGGER AS $$
    DECLARE 
    stat_seans TEXT;
    BEGIN 
        SELECT status INTO stat_seans FROM seans WHERE id_seans = NEW.id_seans;
        IF (NEW.czy_oplacona = TRUE AND stat_seans = 'aktywny') THEN
            UPDATE rezerwacja SET status = 'aktywna' WHERE id_rezerwacja = NEW.id_rezerwacja AND status != 'aktywna';
        END IF;
        RETURN NEW;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER oplrez AFTER INSERT OR UPDATE ON rezerwacja FOR EACH ROW EXECUTE PROCEDURE oplacanie_rezerwacji();

CREATE OR REPLACE FUNCTION aktualne_seanse()
RETURNS VOID AS $$
    DECLARE
    s RECORD;
    BEGIN
        FOR s IN
            SELECT id_seans FROM seans WHERE (data < CURRENT_DATE) OR (data = CURRENT_DATE AND godzina < CURRENT_TIME)
        LOOP
            UPDATE seans SET status = 'nieaktywny' WHERE id_seans = s.id_seans;
            UPDATE rezerwacja SET status = 'nieaktywna' WHERE id_seans = s.id_seans;
        END LOOP;
    END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION dodaj_rezerwacje_id(id_seansu INTEGER, email VARCHAR(100), rzad INTEGER, miejsce INTEGER)
RETURNS VOID AS $$
DECLARE
    klient_id_v INTEGER;
    siedzenie_id_v INTEGER;
    istniejaca_rezerwacja INTEGER;
    wolne_miejsce INTEGER;
BEGIN
    SELECT id_klient INTO klient_id_v 
    FROM klient 
    WHERE mail = email;
    
    IF NOT FOUND THEN 
        RAISE EXCEPTION 'Nie mamy klienta o podanym mailu.';
    END IF;
    
    SELECT id_siedzenia INTO siedzenie_id_v 
    FROM siedzenie 
    JOIN sala USING(id_sali) 
    JOIN seans USING(id_sali) 
    WHERE id_seans = id_seansu
      AND nr_miejsca = miejsce 
      AND nr_rzedu = rzad;

    SELECT id_siedzenia INTO wolne_miejsce
    FROM wolne_miejsca
    WHERE id_siedzenia = siedzenie_id_v;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'To miejsce jest juz zajete.';
    END IF;
    
    SELECT id_rezerwacja INTO istniejaca_rezerwacja 
    FROM rezerwacja 
    WHERE id_seans = id_seansu 
      AND id_klient = klient_id_v 
      AND id_siedzenia = siedzenie_id_v;
    
    IF FOUND THEN
        RAISE EXCEPTION 'Ta rezerwacja juz istnieje.';
    ELSE
        INSERT INTO rezerwacja (id_seans, id_klient, id_siedzenia) 
        VALUES (id_seansu, klient_id_v, siedzenie_id_v);
    END IF;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE FUNCTION dodawanie_karty()
RETURNS TRIGGER AS $$
    BEGIN
    IF (NEW.nr_karty_czlonkowskiej IS NOT NULL AND OLD.nr_karty_czlonkowskiej IS NOT NULL) THEN
        RAISE EXCEPTION 'Uzytkownik o mailu % juz posiada karte czlonkowska.', NEW.mail;
    END IF;
    RETURN NEW;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER dk BEFORE UPDATE ON klient FOR EACH ROW EXECUTE PROCEDURE dodawanie_karty();

CREATE OR REPLACE FUNCTION dodawanie_seansu()
    RETURNS TRIGGER AS $$
    DECLARE
        s RECORD;
        dlugosc_filmu INTEGER;
    BEGIN
        SELECT dlugosc INTO dlugosc_filmu FROM film WHERE id_film = NEW.id_film;
        IF dlugosc_filmu IS NULL THEN
            RAISE EXCEPTION 'Film o ID % nie istnieje', NEW.id_film;
        END IF;
        FOR s IN
            SELECT id_seans, godzina, dlugosc, id_sali FROM seans JOIN film USING(id_film) WHERE seans.data = NEW.data AND seans.id_sali = NEW.id_sali
        LOOP
            IF (s.id_seans != NEW.id_seans) THEN
                IF s.godzina = NEW.godzina THEN
                    RAISE EXCEPTION 'Nie moze byc dwoch seansow o tej samej godzinie.';
                END IF;
            END IF;
            IF s.godzina < NEW.godzina THEN
                IF (NEW.godzina - s.godzina < (s.dlugosc + 60) * INTERVAL '1 minute') THEN
                    RAISE EXCEPTION 'Seans zaczyna sie zbyt wczesnie.';
                END IF;
            ELSIF s.godzina > NEW.godzina THEN
                IF (s.godzina - NEW.godzina < (dlugosc_filmu + 60) * INTERVAL '1 minute') THEN
                    RAISE EXCEPTION 'Seans zaczyna sie zbyt pozno';
                END IF;
            END IF;
        END LOOP;
        RETURN NEW;
    END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER ds BEFORE INSERT OR UPDATE ON seans FOR EACH ROW EXECUTE PROCEDURE dodawanie_seansu();

CREATE VIEW aktywne_seanse AS
    SELECT s.id_seans, tytul, data, godzina, dzwiek, grafika, mail
    FROM seans s JOIN film USING(id_film) 
    LEFT JOIN gdzie_praca gp ON s.id_seans = gp.id_seans 
    LEFT JOIN pracownik p ON p.id_pracownik = gp.id_pracownik
    WHERE s.status = 'aktywny' OR s.status = 'za malo osob';

CREATE VIEW widok_rezerwacje AS
SELECT r.id_rezerwacja, f.tytul, s.data, s.godzina, r.status, r.czy_oplacona, sa.nr_sali, siedzenia.nr_miejsca, siedzenia.nr_rzedu,  k.mail,
    CASE 
        WHEN k.nr_karty_czlonkowskiej IS NOT NULL THEN siedzenia.cena * 0.5 
        ELSE siedzenia.cena 
    END AS cena
FROM rezerwacja r
JOIN siedzenie siedzenia USING(id_siedzenia)
JOIN seans s USING(id_seans)
JOIN sala sa ON s.id_sali = sa.id_sali
JOIN film f USING(id_film)
JOIN klient k ON r.id_klient = k.id_klient;

CREATE VIEW wolne_miejsca AS
SELECT DISTINCT siedzenie.id_siedzenia, siedzenie.nr_miejsca, siedzenie.nr_rzedu, seans.id_seans
FROM siedzenie
JOIN seans USING(id_sali)
LEFT JOIN rezerwacja 
    ON siedzenie.id_siedzenia = rezerwacja.id_siedzenia 
    AND seans.id_seans = rezerwacja.id_seans
WHERE rezerwacja.id_rezerwacja IS NULL
ORDER BY seans.id_seans, siedzenie.nr_rzedu, siedzenie.nr_miejsca;

CREATE VIEW grane_filmy AS
SELECT DISTINCT tytul, oryginalny_tytul, opis, dlugosc, kraj_produkcji, data_premiery, ograniczenia_wiekowe, nazwa_gatunku
FROM film LEFT JOIN jaki_gatunek USING(id_film) LEFT JOIN gatunek USING(id_gatunek)
JOIN seans USING(id_film)
WHERE seans.status = 'za malo osob' OR seans.status = 'aktywny';

